name: Build and deploy .NET application to container app webapplication31-app-20220429080
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: webapplication2
  CONTAINER_APP_NAME: webapplication31-app-20220429080
  CONTAINER_APP_RESOURCE_GROUP_NAME: aapt0429LinuxGroup
  CONTAINER_REGISTRY_LOGIN_SERVER: webapplication3120220429081010.azurecr.io
  DOCKER_FILE_PATH: WebApplication31/Dockerfile
  PROJECT_NAME_FOR_DOCKER: webapplication31
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.WebApplication3120220429081010_USERNAME_FFFF }}
        password: ${{ secrets.WebApplication3120220429081010_PASSWORD_FFFF }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.webapplication31_app_20220429080_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.WebApplication3120220429081010_USERNAME_FFFF }} --password ${{ secrets.WebApplication3120220429081010_PASSWORD_FFFF }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
